import type {Metadata}
from "next";
import "./globals.css";
import Footer from "@/components/Footer";
import Header from "@/components/Header";
import {CartProvider} from '@/contexts/CartContext';

export const metadata: Metadata = {
    title: "Zevra",
    description: "Generated by create next app"
};

export default function RootLayout({children} : {
    children : React.ReactNode
}) {
    return (
        <html>
            <body>
                <CartProvider>
                    <Header/>
                    <main>{children}</main>
                    <Footer/>
                </CartProvider>
            </body>
        </html>
    );
}
